### ISSUE TITLE
Meta: This should be a PR, not a repo

### ISSUE THREAD

**Issue by littledan** [justingrant/proposal-canonical-tz#3]
This does not add a new API and the possible changes to semantics are small and subtle. I think this should be proposed as a consensus-seeking PR, and doesn't make sense to put at a stage or have in its own repo.

**Comment by justingrant** [comment]
Hi Dan, thanks for checking in. I'm happy to accmommodate whatever is the best way to achieve the changes described in the README. We're proposing it for Stage 1 because that's what @sffc (without disagreement from anyone else) recommended at the TG2 meeting last week.

Maybe you and Shane could come to agreement on how best to proceed?  cc @gibson042

> This does not add a new API

This proposal [includes](https://github.com/justingrant/proposal-canonical-tz#6-add-temporaltimezoneprototypeequals) a new API: `Temporal.TimeZone.prototype.equals`. Does this affect your suggestion that it shouldn't be a separate proposal?

I'll push an update to the agenda item to add a link to the slides, which cover the same content as the README but might be a quicker read so maybe other folks won't miss the new API.

> possible changes to semantics are small and subtle

Yep, agree that these [changes](https://github.com/justingrant/proposal-canonical-tz#5-defer-link-traversing-canonicalization) are small. If it's better to make them as a proposal-less consensus PR, I'm OK with that. But they are somewhat paired with the new API, because the main reason that the new API exists because of these changes in semantics. So it may makes sense to bundle them together.  Happy to follow whatever is the right process here.

**Comment by justingrant** [comment]
BTW, here's [slides](https://docs.google.com/presentation/d/13vW8JxkbzyzGubT5ZkqUIxtpOQGNSUlguVwgcrbitog/edit#slide=id.p) in case you want a quicker read.

**Comment by littledan** [comment]
Apologies for my quick and incomplete read. Yes, shorter text is nice when possible.

**Comment by justingrant** [comment]
Cool. Can we close this issue?

Sent from my mobile device. Apologies for any typos.
________________________________

**Comment by sffc** [comment]
We've learned from experience that normative PRs are not good vehicles for carrying substantive, potentially controversial changes, which is how I would describe this change. This is definitely a user-visible change, even if the spec change is small. I'd rather err on the side of a process that is too heavy but gets the job done well than a process that is too light and doesn't account for all contingencies.

**Comment by justingrant** [comment]
Given that we just reached Stage 1, I think we can close this issue. :-)
